(setq og/math-global-snippets
      '(("\\Ricsl" "\\slashed{\\Ric}") ("\\Riemsl" "\\slashed{\\Riem}")
        ("Riem" "\\Riem") ("\\Curl sl" "\\slashed{\\Curl}\\,")
        ("curl" "\\Curl ") ("XX" "\\times ")
        ("RHS" "\\side{RHS}{`(read-string \"Enter reference: \")`}")
        ("LHS" "\\side{LHS}{`(read-string \"Enter reference: \")`}")
        ("^\\ast{}o" "s\\to{}") ("txt" "\\textnormal{$0}") ("ll" "\\ll ")
        ("ubr" "\\underbrace{$1}_{$2}") ("gg" "\\gg ") ("gsim" "\\gtrsim ")
        ("\\dd{}vol" "\\dd{}\\vol") ("\\Grad til" "\\tilde{\\Grad{}}")
        ("\\,hd" "\\ast{}\\!") ("hd" "\\ast{}\\!")
        ("\\slashed{\\Grad{}}4" "\\slashed{\\Grad{}}_4")
        ("\\slashed{\\Grad{}}3" "\\slashed{\\Grad{}}_3")
        ("\\otimes hat" "\\widehat{\\otimes}")
        ("\\hat{\\chi}un" "\\hat{\\underline{\\chi}}")
        ("\\chi{}hat" "\\hat{\\chi}") ("\\Div sl" "\\slashed{\\Div}\\,")
        ("\\mathcal{L}sl" "\\slashed{\\mathcal{L}}") ("un" "underline" t)
        ("div" "\\Div ") ("div " "\\Div ") ("\\Grad sl" "\\slashed{\\Grad{}}")
        ("sl" "slashed" t) ("def" "\\deft{$0}") ("dot" "physics-dot" t)
        ("Loo" "L^\\infty") ("L2" "L^2") ("Rn" "\\R^n")
        ("\\subset eq" "\\subseteq ") ("_int" "iintegral" t) ("Ric" "\\Ric")
        ("Sff" "\\Sff") ("\\Lapl /" "\\slashed{\\Lapl{}}")
        ("\\Gal(" "\\Gal($0)") ("\\partialun" "\\underline{\\partial{}}")
        ("\\partial{}un" "\\underline{\\partial{}}")
        ("\\Box{}til" "\\widetilde{\\Box{}}") ("_inn" "i\\in ")
        ("\\partial{}bar" "\\conj{\\partial}") ("Diff" "\\Diff")
        ("\\Grad /" "\\slashed{\\Grad{}}") ("Gr" "\\Gr") ("ls" "\\lesssim ")
        ("Ann" "\\Ann ") ("check" "\\check{$1}") ("Hilb" "\\Hilb")
        ("cap" "\\frown{}") ("cup" "\\smile{}")
        ("\\leftarrow{}^" "\\xleftarrow{$0}") ("Ext" "\\Ext")
        ("ot" "\\leftarrow{}") ("mSpec" "\\mSpec") ("Proj" "\\Proj")
        ("Alg" "\\Alg") ("Sch" "\\Sch") ("^dt" "^dt") ("shom" "\\SheafHom")
        ("pipe" "|") ("physics-dot" "physics-dot" t) (":=" "\\\\coloneqq{}")
        ("iso" "isomorphism" t) ("dash" "dashed" t) ("surj" "surjective" t)
        ("inj" "injective" t) ("Coo" "C^\\infty") ("loc" "_{\\text{loc}}")
        ("\\to v" "t/") ("PGL" "\\PGL") ("disc" "\\Disc ") ("Supp" "\\Supp ")
        ("sdx" "\\rtimes ") ("diag" "\\Diag") ("OO" "\\Or") ("SU" "\\SU")
        ("Mat" "\\Mat") ("SO" "\\SO") ("Ind" "\\Ind") ("odot" "\\odot{}")
        ("\\abs{*" "\\abs[\\Big]{") ("bf" "\\mathbf{$1}") ("dto" "\\searrow ")
        ("codim" "\\Codim ") ("upto" "\\nearrow ") ("opr" "outer-product" t)
        ("\\to ^" "\\xrightarrow{$0}") ("avint" "\\avint ")
        ("bb" "\\mathbb{$0}") ("bket" "\\braket{$1}{$2}") ("ket" "\\ket{$1}")
        ("succ" "\\prec ") ("bul" "\\bullet{}") ("Sh" "\\Sh")
        ("cprod" "\\coprod_{$1}") ("PSh" "\\PreSh") ("EE" "\\E{}")
        ("PP" "\\Prob{}") ("_inv" "i^{-1}") ("End" "\\End") ("coker" "\\Coker ")
        ("Bil" "\\Bil") ("\\subset *" "\\supset ") ("HH" "\\HH") ("Mod" "\\Mod")
        ("esup" "\\Esup ") ("AGrp" "\\AGrp") ("dual" "^{\\dual}")
        ("ddual" "^{\\dual}") ("^{\\dual}dual" "^{\\ddual}") ("Nat" "\\Nat")
        ("Ring" "\\Ring") ("Hom" "\\Hom") ("Id" "\\Id") ("Cod" "\\Cod")
        ("Dom" "\\Dom") ("Mor" "\\Mor") ("fr" "\\mathfrak{$0}")
        ("\\to iso" "\\xrightarrow{\\sim}") ("\\to by" "\\xrightarrow{$1}")
        ("wto" "\\rightharpoonup ") ("^pd" "^pd") ("\\tan h" "\\tanh ")
        ("\\sec h" "\\sech ") ("what" "\\widehat{$0}") (">>" "&>") ("<<" "&<")
        ("DD" "\\D{}") ("ipr" "\\intprod{}") ("WW" "\\wedge{}")
        ("SP" "equation-to-split" t) ("\\ge ge" "&\\ge ") ("\\le le" "&\\le ")
        ("asym" "^{\\Asym}") ("sym" "^{\\Sym}") ("res" "\\Res ")
        ("ome" "m_{\\ast{}}") ("vol" "\\Vol ") ("Log" "\\Log ")
        ("sub" "\\substack{$0}") ("var" "\\Var") ("#" "\\card{}")
        ("Tor" "\\Tor ") ("qqd" "\\qquad ") ("qd" "\\quad ")
        ("zsum" "\\sum_{n\\in\\Z} ") ("spec" "\\Spec ") ("Gal" "\\Gal($0)")
        ("gal" "\\Gal($0)") ("ov" "/") ("sgn" "\\Sgn ") ("op" "_{\\Op}")
        ("Q[" "\\Q[$0]") ("dist" "\\Dist ") ("\\sin n" "s\\in{}")
        ("loo" "\\ell^{\\infty}") ("Im" "\\Im ") ("Re" "\\Re ") ("Z[" "\\Z[$0]")
        ("C[" "\\C[$0]") ("dmat " "diagonal-matrix" t) ("nn" "_n") ("mm" "_m")
        ("ii" "_i") ("jj" "_j") ("_nn" "_nn") ("_mm" "_mm") ("_ii" "_ii")
        ("nm" "\\norm{$0}") ("norm" "\\norm{$0}") ("rad" "\\Rad ")
        ("Hess" "\\Hess ") ("mid" "\\mid{}") ("mati " "identity-matrix" t)
        ("mat " "matrix" t) ("sp " "split" t) ("ndiv" "\\nmid ")
        ("adj" "\\Adj ") ("rref" "\\rref ") ("text" "\\textnormal{$0}")
        ("num" "\\num{$0}") ("perp" "\\perp ") ("nsg" "\\normsg ") ("SL" "\\SL")
        ("\\pinn" "p\\in ") ("Aut" "\\Aut") ("md" "\\pmod ") ("pmod" "\\pmod ")
        ("{" "{$0}") ("khat" "\\khat") ("jhat" "\\jhat") ("ihat" "\\ihat")
        ("ilim" "\\varprojlim ") ("dlim" "\\varinjlim ") ("\\Z/" "z-mod-n" t)
        ("Z/" "z-mod-n" t) ("rvec" "row-vector" t) ("cvec" "column-vector" t)
        ("<!" "\\triangleleft{}") ("=<" "\\impliedby{}") ("frac" "frac" t)
        ("ell" "\\ell{}") ("epr" "\\prod_{$0}") ("cdsq" "commutative-square" t)
        ("cdtr" "commutative-triangle" t) ("frob" "\\Frob")
        ("lg" "\\legendre{$1}{$2}$0") ("st" "^\\ast{}") ("ast" "\\ast{}")
        ("til" "tilde" t) ("VV" "\\vee{}") ("FF" "field" t) ("iff" "\\iff ")
        ("Ptop" "\\PTop") ("Grp" "\\Grp") ("Top" "\\Top") ("Vect" "\\Vect")
        ("Set" "\\Set") ("obj" "\\Obj") ("mst" "m^\\star{}") ("circ" "\\circ ")
        ("Min" "\\min ") ("max" "\\max ") ("\\subset neq" "\\subsetneq ")
        ("frak" "\\mathfrak{$0}") ("~" "\\sim ") ("~" "sim" t)
        ("mod" "quotient-helper" t) ("lcm" "\\LCM") ("gcd" "\\GCD")
        ("ang" "\\langle{}$0\\rangle{}") ("aut" "\\Aut($0)") ("GL" "\\GL")
        ("ntin" "\\notin ") ("not" "\\not ") ("deg" "\\Deg ")
        ("conj" "\\conj{$0}") ("inp" "\\inp{${1:\\cdot}}{${2:\\cdot}}$0")
        ("esum" "\\sum_{$0}") ("<-" "\\leftarrow") ("CP" "\\CP") ("RP" "\\RP")
        ("scr" "\\mathscr{$0}") ("hom" "\\Hom") ("cal" "\\mathcal{$0}")
        ("!>" "\\mapsto ") ("==" "cong-or-split-equals" t) ("=>" "\\implies ")
        ("(" "($0)") ("CC" "\\C") ("NN" "\\N") ("QQ" "\\Q") ("RR" "\\R")
        ("ZZ" "\\Z") ("[" "[$0]") ("{}^" "superscript" t) ("^" "superscript" t)
        ("_" "subscript" t) ("abs" "\\abs{$0}") ("acos" "\\arccos ")
        ("acot" "\\arccot ") ("aleph" "\\aleph") ("approx" "\\approx ")
        ("asin" "\\arcsin ") ("atan" "\\arctan ") ("bar" "bar" t)
        ("big" "big-operator" t) ("nck" "\\binom{${1:n}}{${2:k}}$0")
        ("box" "\\Box{}") ("cases" "cases" t) ("cb" "^3") ("cc" "\\subset ")
        ("ceil" "\\ceil{$0}") ("comp" "^\\complement ") ("cong" "\\equiv ")
        ("cos" "\\cos ") ("cot" "\\cot ") ("dd" "derivative" t)
        ("del" "\\partial{}") ("det" "\\Det ") ("dim" "\\Dim ")
        ("dint" "dintegral" t) ("dv" "\\dv{$1}{${2:x}}$0") ("exp" "\\exp ")
        ("faa" "\\forall ") ("flo" "\\floor{$0}") ("ge" "\\ge ")
        ("gr" "\\Grad ") ("hat" "hat" t) ("iint" "iintegral" t)
        ("im" "\\Image ") ("inf" "infimum" t) ("inn" "\\in ")
        ("int" "integral" t) ("inv" "^{-1}") ("ker" "\\Ker ") ("lap" "\\Lapl ")
        ("lb" "label" t) ("le" "\\le ") ("lim" "\\lim ")
        ("elim" "\\lim_{${1:n}\\to{}${2:\\infty}}$0")
        ("list" "${1:a}_{${2:1}},\\ldots,$1_{${3:n}}") ("ln" "\\ln ")
        ("log" "\\log ") ("lr(" "\\left({}$0\\right){}")
        ("lr[" "\\left[{}$0\\right]{}") ("lr{" "\\set{$0}") ("mp" "\\mp ")
        ("nabl" "\\nabla ") ("ndd" "\\dd[${1:n}]{${2:x}}$0")
        ("ndv" "\\dv[${1:n}]{$2}{${3:x}}$0") ("neq" "\\neq{}")
        ("npd" "\\partial[${1:n}]{$2}{${3:x}}$0")
        ("npv" "\\partialv[${1:n}]{$2}{${3:x}}$0")
        ("nsq" "\\sqrt[${1:n}]{$2}$0") ("o+" "\\oplus ") ("oint" "ointegral" t)
        ("oo" "\\infty") ("opl" "\\oplus ") ("ox" "\\otimes ")
        ("part" "\\partial{}") ("pd" "\\partial{}") ("pm" "\\pm ")
        ("prod" "\\prod_{${1:k}=${2:0}}^{${3:n}} $0") ("prop" "\\propto ")
        ("pas" "pairsum" t) ("psum" "pairsum" t) ("pv" "\\pdv{$1}{${2:x}}$0")
        ("sec" "\\sec ") ("seq" "\\set{${1:a}_${2:n}}_{$2\\in${4:\\N}}$0")
        ("set" "\\set{$0}") ("sim" "\\sim ") ("sin" "\\sin ") ("span" "\\Span ")
        ("sq" "\\sqrt{$0}") ("{}sr" "^2") ("sr" "^2") ("star" "^\\star ")
        ("sum" "\\sum_{${1:n}=${2:0}}^{${3:\\infty}}") ("sup" "supremum" t)
        ("tan" "\\tan ") ("then" "\\implies ") ("to" "\\to ") ("tr" "\\Tr ")
        ("vv" "\\vec ") ("xii" "x_i")))
